require:
  - rubocop-rails
  - standard

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

  Exclude:
    - db/**/*
    - vendor/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - development
    - test
    - staging
